name: Magisk Build

on:
  workflow_dispatch:
    inputs:
      MAGISK_REPO:
        description: 'Magisk Repository'
        required: true
        default: 'https://github.com/topjohnwu/Magisk'
      MAGISK_BRANCH:
        description: 'Magisk Repository Branch'
        required: true
        default: 'master'

jobs:
  build:
    name: Build Magisk
    runs-on: ubuntu-latest
    env:
      SCCACHE_DIRECT: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Clone Magisk
        run: |
          git clone --recurse-submodules ${{ inputs.MAGISK_REPO }} -b ${{ inputs.MAGISK_BRANCH }} ./Magisk
          echo "MAGISK_VERS=$(awk -F'=' '/magisk.versionCode/ {print $2}' Magisk/gradle.properties)" >> $GITHUB_ENV

      - name: Setup environment [1]
        uses: ./.github/actions/setup

      - name: Setup environment [2]
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --only-upgrade libstdc++6

      - name: Build release
        run: cd Magisk && ./build.py -vr all

      - name: Build debug
        run: cd Magisk && ./build.py -v all

      - name: Stop gradle daemon
        run: cd Magisk && ./gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: Magisk/out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-symbols
          path: Magisk/app/build/outputs
          compression-level: 9

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Magisk/out/app-release.apk
            Magisk/out/app-debug.apk
          name: Unofficial Magisk Build Release v${{ env.MAGISK_VERS }}
          tag_name: ${{ github.run_id }}
          body: |
            ## Resources
            - [Magisk Repository](${{ inputs.MAGISK_REPO }}/tree/${{ inputs.MAGISK_BRANCH }})
            ## Available Downloads
            - Release, for normal usage.
            - Debug, solely for debugging purposes.
            ## Notes
            - I, carlodandan, won't entertain any flashing/app/patching issue. Contact whoever the maintainer of the Magisk repository you used for building. Again, the builder you used is for personal use only. I am not responsible with any of the error upon flashing or patching.
